export const pageContent: Record<string, { eyebrow: string; title: string; copy: string; actions: string[] }> = {
  properties: { eyebrow: "Verified listings", title: "Find a property worth visiting.", copy: "Browse public area details, amenities, approved hosts and available viewing times without exposing private owner data.", actions: ["Search by area", "Compare deposits", "Review host status"] },
  "properties/modern-apartment": { eyebrow: "Property details", title: "Modern 2-bed apartment", copy: "Greenway, Horizon District · 2 beds · 2 baths · 78 m². Attendance deposit: 0.5 XLM.", actions: ["Choose a slot", "Read deposit rules", "Book a viewing"] },
  book: { eyebrow: "Booking", title: "Review before you reserve.", copy: "The Mainnet escrow refunds a pre-visit cancellation or a host-confirmed visit.", actions: ["Select viewing time", "Accept visible rules", "Fund on Mainnet"] },
  "booking/receipt": { eyebrow: "Receipt", title: "Your escrow timeline.", copy: "Created → Funded → Checked in → Visit confirmed → Refunded. Every transaction state includes its public explorer reference.", actions: ["View booking state", "Open transaction history", "Download receipt"] },
  renter: { eyebrow: "Renter dashboard", title: "Bookings, check-ins and refunds.", copy: "Track pending signatures, upcoming appointments, confirmation deadlines, disputes and completed settlements.", actions: ["Upcoming viewings", "Transaction history", "Submit feedback"] },
  host: { eyebrow: "Host workspace", title: "Run trustworthy viewings.", copy: "Create listings, publish non-overlapping slots, confirm attendance and respond to disputes with an auditable history.", actions: ["Create listing", "Manage slots", "Review bookings"] },
  "host/listings/new": { eyebrow: "Listing creation", title: "Publish only what renters need.", copy: "Add public area, amenities, accessible images and availability. Approval is required before a listing appears in search.", actions: ["Add property details", "Upload images", "Submit for review"] },
  "host/slots": { eyebrow: "Availability", title: "Viewing-slot management.", copy: "Capacity, short payment locks and overlap checks protect every appointment from double booking.", actions: ["Create a slot", "Review locks", "Pause availability"] },
  "check-in": { eyebrow: "Secure check-in", title: "Prove the visit without exposing location.", copy: "One-time QR challenges expire quickly and bind the booking, slot and nonce. A camera-free manual fallback is always available.", actions: ["Scan QR", "Use manual code", "Request help"] },
  "attendance": { eyebrow: "Attendance", title: "Confirm what happened.", copy: "Confirm a completed visit or report a no-show within the disclosed window. Settlement never relies on browser state alone.", actions: ["Confirm visit", "Report renter no-show", "Report host no-show"] },
  cancel: { eyebrow: "Cancellation", title: "Know the outcome before confirming.", copy: "The current booking state and deadline determine whether the deposit is refunded and whether a disclosed cancellation fee applies.", actions: ["Review outcome", "Confirm cancellation", "Keep booking"] },
  "disputes/new": { eyebrow: "Dispute creation", title: "Pause settlement and present evidence.", copy: "Only booking participants can open an eligible dispute. Evidence is access-controlled and hashed before an on-chain reference.", actions: ["Describe issue", "Attach evidence", "Submit dispute"] },
  disputes: { eyebrow: "Dispute details", title: "A transparent resolution record.", copy: "Both parties can respond. Only the configured arbitrator can resolve an open dispute, with a required reason.", actions: ["Review evidence", "Add response", "Track resolution"] },
  admin: { eyebrow: "Moderation", title: "Protect listings without controlling funds.", copy: "Approve hosts, disable suspicious listings, review audit logs and pause new booking creation during an emergency.", actions: ["Host applications", "Listing review", "Audit logs"] },
  arbitration: { eyebrow: "Arbitrator", title: "Resolve only eligible disputes.", copy: "Review both sides, state the reason and choose a contract-permitted refund, release or split settlement.", actions: ["Review case", "Set resolution", "Publish reason"] },
  transactions: { eyebrow: "Transaction history", title: "Every settlement, traceable.", copy: "See pending, failed and completed contract actions with network, amount, status and explorer link.", actions: ["Filter history", "Open explorer", "Export receipt"] },
  help: { eyebrow: "Help center", title: "Clear answers at every step.", copy: "Learn how deposits work, recover from a rejected signature, use manual check-in and understand dispute windows.", actions: ["Wallet help", "Booking help", "Contact support"] },
  docs: { eyebrow: "Documentation", title: "Build and use the protocol safely.", copy: "User guides, contract state transitions, API reference, Mainnet deployment evidence and security reviews live together.", actions: ["Renter guide", "Host guide", "API reference"] },
  security: { eyebrow: "Security", title: "Trust comes from enforced limits.", copy: "Strict state transitions, replay-safe challenges, one-time settlement and auditable admin actions protect every booking.", actions: ["Threat model", "Contract review", "Report a vulnerability"] }
};

export const staticPaths = Object.keys(pageContent).map((path) => ({ slug: path.split("/") }));
